version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run tests
          command: gradle test
      - store_test_results:
          path: build/test-results
      - run:
          name: Make jar
          command: gradle jar
      - store_artifacts:
          path: build/libs
