version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run tests
          command: gradle test
      - store_test_results:
          path: build/test-results
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Make jar
          command: gradle jar
      - store_artifacts:
          path: build/libs
workflows:
  version: 2
  test_and_package:
    jobs:
      - test
      - package:
          requires:
            - test
