version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run tests
          command: gradle test
      - store_test_results:
          path: build/test-results
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Make jar
          command: gradle jar
      - store_artifacts:
          path: build/libs
  dockerize:
    machine: true
    steps:
      - checkout
      # Login to docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # build the application image
      - run: docker build -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .
      # deploy the image
      - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1
workflows:
  version: 2
  test_and_package:
    jobs:
      - test
      - package:
          requires:
            - test
      - dockerize:
          requires:
            - package
